/* SRS Vision clean SPA — one router, one state store, separate dashboards, local fallback. */
(function(){
  'use strict';

  const MEMBERS=['Gagan R','Teja Sawaroop','G M Chinmayee','Deepika N S','Sinchana J','Geetha H K','Gangaraju K V','Ganesh K','Girish M S','Gagana H R','Gangothri H R','Prabhakar'];
  const TOOLS={
    'graphic-design':{icon:'✦',title:'Graphic Design',desc:'Brand identity, social creatives, posters, thumbnails, print design and creative production.',features:['Brand Identity','Social Creatives','Posters & Flyers','Thumbnails','Print Design','Template Library']},
    'ai-tools':{icon:'✦',title:'AI Tools',desc:'One workspace to launch ChatGPT, Gemini, Claude, Copilot and Perplexity.',features:['ChatGPT','Gemini','Claude','Microsoft Copilot','Perplexity','Prompt Library']},
    'video-tools':{icon:'▶',title:'Video Tools',desc:'A dedicated production workspace for editing, conversion, compression and subtitles.',features:['Video Editor','Compressor','Converter','GIF Maker','Subtitles','Screen Recorder']},
    'image-tools':{icon:'▧',title:'Image Tools',desc:'Edit, enhance, resize, compress and convert visual assets in one place.',features:['Image Editor','Upscaler','Background Remover','Converter','Compressor','AI Image Generator']},
    'document-tools':{icon:'▤',title:'Document Tools',desc:'Create and transform business documents without leaving SRS Vision.',features:['Document Editor','DOCX Tools','Merge Documents','Templates','eSign','Convert Documents']},
    'pdf-tools':{icon:'▥',title:'PDF Tools',desc:'Merge, split, convert, sign and organize PDF files.',features:['PDF Editor','PDF to Word','Word to PDF','Merge PDF','Split PDF','eSign']},
    'productivity-tools':{icon:'✓',title:'Productivity',desc:'Tasks, notes, focus sessions, habits and recurring workflows.',features:['Task Manager','Notes','To-Do List','Pomodoro','Habit Tracker','Time Tracker']},
    'developer-tools':{icon:'</>',title:'Developer Tools',desc:'Code, test, format and inspect technical work.',features:['Code Editor','JSON Formatter','Regex Tester','API Tester','Git Tools','Terminal']},
    'business-tools':{icon:'₹',title:'Business Tools',desc:'Operations tools for invoices, clients, budgets, reports and planning.',features:['Invoice Generator','Quotation','CRM','Report Generator','Budget Planner','Inventory']},
    'education-tools':{icon:'⌘',title:'Education Tools',desc:'Courses, notes, quizzes, flashcards, research and learning tracking.',features:['Courses','Study Notes','Quiz & Tests','Flashcards','Research','Learning Tracker']},
    'entertainment-tools':{icon:'♫',title:'Entertainment',desc:'Games, music, movies, streaming and visual discovery.',features:['Games','Music','Movie Search','Wallpapers','Live TV','Streaming']},
    'utilities-tools':{icon:'⌁',title:'Utilities',desc:'Useful everyday tools for calculations, conversions, QR and text tasks.',features:['Calculator','Color Picker','Unit Converter','QR Generator','Password Generator','Text Tools']}
  };
  const AI_LINKS=[['ChatGPT','https://chatgpt.com/','AI chat and creation'],['Gemini','https://gemini.google.com/','Google AI workspace'],['Claude','https://claude.ai/','AI writing and analysis'],['Microsoft Copilot','https://copilot.microsoft.com/','Microsoft AI assistant'],['Perplexity','https://www.perplexity.ai/','AI search and research']];
  const SOCIAL=[['WhatsApp Business','💬','https://business.whatsapp.com/','Messaging'],['Instagram','◎','https://www.instagram.com/','Social'],['YouTube Studio','▶','https://studio.youtube.com/','Video'],['Pinterest','◈','https://business.pinterest.com/','Visual'],['Facebook','f','https://www.facebook.com/business/','Social'],['LinkedIn','in','https://www.linkedin.com/','Professional'],['Telegram','✈','https://web.telegram.org/','Messaging'],['X','𝕏','https://x.com/','Social']];
  const routes=[
    ['dashboard','⌂','Dashboard'],['projects','▣','Projects'],['clients','♙','Clients'],['teams','♧','Teams'],['services','◈','Services'],['graphic-design','✦','Graphic Design'],['social-media','◉','Social Media'],['ai-tools','✦','AI Tools'],['video-tools','▶','Video'],['image-tools','▧','Images'],['document-tools','▤','Documents'],['pdf-tools','▥','PDF'],['productivity-tools','✓','Productivity'],['developer-tools','</>','Developer'],['business-tools','₹','Business'],['education-tools','⌘','Education'],['entertainment-tools','♫','Entertainment'],['utilities-tools','⌁','Utilities'],['notifications','🔔','Notifications'],['money-transfer','💸','Money Transfer'],['files','📁','Files'],['calendar','📅','Calendar'],['reports','▥','Reports'],['accounts','₹','Accounts'],['bank','🏦','Bank'],['meetings','🤝','Meetings'],['announcements','📢','Announcements'],['contacts','☎','Contacts'],['database','◉','Database'],['settings','⚙','Settings']
  ];
  const stateKey='srsVisionState';
  const defaultState={
    company:{name:'SRS Vision',tagline:'YOUR VISION · OUR CREATION'},
    members:MEMBERS.map((name,i)=>({id:'m'+(i+1),name,role:'SRS Vision Member',service:'Creative Team',description:'',active:true,skills:'',phone:'',notes:''})),
    projects:[
      {id:'p1',name:'Brand Identity Project',client:'Nova Media',service:'Graphic Design',status:'In Progress',due:'2026-10-08',value:25000,owner:'Gagan R'},
      {id:'p2',name:'Website Launch',client:'ABC Enterprises',service:'Web Development',status:'Planning',due:'2026-10-15',value:42000,owner:'Teja Sawaroop'},
      {id:'p3',name:'Social Campaign',client:'GreenLeaf Foods',service:'Social Media',status:'Active',due:'2026-10-03',value:18000,owner:'G M Chinmayee'}
    ],
    clients:[{id:'c1',name:'Nova Media',service:'Branding',status:'Active',contact:'+91 90000 00002'},{id:'c2',name:'ABC Enterprises',service:'Website',status:'Active',contact:'+91 90000 00001'},{id:'c3',name:'GreenLeaf Foods',service:'Social Media',status:'Lead',contact:'+91 90000 00003'}],
    services:[{id:'s1',name:'Graphic Design',description:'Brand identity and visual creatives',status:'Active'},{id:'s2',name:'Web Development',description:'Websites and digital experiences',status:'Active'},{id:'s3',name:'Social Media',description:'Content, channels and campaigns',status:'Active'}],
    socialChannels:SOCIAL.map((x,i)=>({id:'ch'+i,name:x[0],icon:x[1],url:x[2],type:x[3],connected:false})),
    notifications:[{id:'n0',source:'System',title:'Welcome to SRS Vision',detail:'Your all-in-one workspace is ready.',createdAt:new Date().toISOString(),read:false}],
    events:[],transactions:[],transfers:[],files:[],settings:{theme:'neon'}
  };
  let state=loadState();
  let currentRoute=(location.hash||'#dashboard').slice(1)||'dashboard';
  let saveTimer=null;

  function clone(v){try{return structuredClone(v)}catch{return JSON.parse(JSON.stringify(v))}}
  function loadState(){try{const x=JSON.parse(localStorage.getItem(stateKey)||'null');return mergeDefaults(x)}catch{return clone(defaultState)}}
  function mergeDefaults(x){const s=clone(defaultState);if(x&&typeof x==='object'){for(const k of Object.keys(s)){if(x[k]!==undefined)s[k]=x[k]}}return s}
  function persist(patchKeys){localStorage.setItem(stateKey,JSON.stringify(state));window.dispatchEvent(new CustomEvent('srs:state-local-change',{detail:{patch:patchKeys?patchKeys.reduce((o,k)=>(o[k]=clone(state[k]),o),{}):clone(state)}}));}
  function commit(keys){persist(keys);render();toast('Saved');}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
  function initials(name){return String(name||'SRS').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join('')||'SR'}
  function toast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
  function setRoute(route){if(!route)return;currentRoute=route;history.replaceState(null,'','#'+route);render()}
  function openExternal(url){window.open(url,'_blank','noopener,noreferrer')}
  function appStatus(){return window.srsDB?.getStatus?.()||{connected:false,realtime:false,pending:false,lastError:''}}

  function sidebar(){
    const main=routes.slice(0,5), creative=routes.slice(5,18), ops=routes.slice(18);
    const group=(title,arr)=>`<div class="nav-title">${title}</div><div class="nav-group">${arr.map(([r,i,l])=>`<button class="nav ${currentRoute===r?'active':''}" data-route="${r}"><span class="ico">${i}</span><span>${l}</span></button>`).join('')}</div>`;
    return `<aside class="sidebar"><div class="brand"><img src="assets/srs-vision-logo.png" alt="SRS Vision"><div><b>SRS VISION</b><small>ALL-IN-ONE PLATFORM</small></div></div>${group('MAIN',main)}${group('CREATIVE TOOLS',creative)}${group('WORKSPACE',ops)}<div class="sidebar-bottom"><div class="live-pill"><span class="dot ${appStatus().connected?'live':'warn'}"></span><span>${appStatus().connected?'Database connected':'Local fallback'}</span></div></div></aside>`;
  }
  function topbar(){return `<div class="topbar"><div class="search"><input id="global-search" placeholder="Search SRS Vision…"></div><div class="top-actions"><button class="top-btn" data-route="notifications">🔔 <span id="notif-count">${state.notifications.filter(n=>!n.read).length}</span></button><button class="top-btn" data-route="database">◉ Live</button><div class="profile"><span class="avatar">${initials('Gagan R')}</span><span>Gagan R</span></div></div></div>`}
  function layout(content){return `<div class="app-shell">${sidebar()}<main class="main">${topbar()}<div class="page">${content}</div></main><nav class="mobile-nav">${routes.slice(0,5).map(([r,i,l])=>`<button class="${currentRoute===r?'active':''}" data-route="${r}">${i}<br>${l.slice(0,7)}</button>`).join('')}</nav></div>`}

  function renderMain(){
    const active=state.projects.filter(p=>['Active','In Progress','Planning'].includes(p.status)).length;
    const revenue=state.projects.reduce((a,p)=>a+Number(p.value||0),0);
    const cards=[['Projects',state.projects.length,'blue'],['SRS Vision Members',state.members.length,'purple'],['Active Work',active,'cyan'],['Pipeline Value',money(revenue),'pink']];
    const toolSlots=Object.entries(TOOLS).map(([k,v])=>`<button class="slot" data-route="${k}"><span class="slot-icon">${v.icon}</span><b>${v.title}</b><small>${esc(v.desc)}</small></button>`).join('');
    const projects=state.projects.slice(0,5).map(p=>`<div class="row"><div><b>${esc(p.name)}</b><small style="display:block;color:#86a4be">${esc(p.client)} · ${esc(p.service)} · ${esc(p.owner)}</small></div><div><span class="status ${p.status==='Active'||p.status==='In Progress'?'ok':'warn'}">${esc(p.status)}</span></div></div>`).join('')||`<div class="row">No projects yet</div>`;
    const people=state.members.slice(0,6).map(m=>`<div class="row"><div style="display:flex;align-items:center;gap:9px"><span class="avatar">${initials(m.name)}</span><div><b>${esc(m.name)}</b><small style="display:block;color:#86a4be">${esc(m.role)}</small></div></div><span class="status ok">Active</span></div>`).join('');
    return layout(`<section class="hero"><div class="hero-copy"><div class="eyebrow">SRS VISION · MAIN DASHBOARD</div><h1>Your vision.<br><span>Our creation.</span></h1><p>A clean launch center for every SRS Vision dashboard, with creative tools, operations, social channels, AI platforms, finance controls and team workflows.</p><div class="pills"><span class="pill">30+ Dashboards & Tools</span><span class="pill">12 SRS Vision Members</span><span class="pill">Realtime-ready</span></div></div><div class="hero-art"><div class="badge"><b>SRS Vision</b><small>Creative + Business Workspace</small></div></div></section>
      <div class="grid4">${cards.map(c=>`<div class="kpi ${c[2]}"><span>${c[0]}</span><b>${c[1]}</b><small>Live workspace metric</small></div>`).join('')}</div>
      <section class="section"><div class="section-head"><div><h2>Tool Launch Center</h2><small>Every tool opens in its own dedicated dashboard</small></div></div><div class="panel"><div class="slot-grid">${toolSlots}</div></div></section>
      <section class="section"><div class="two-col"><div class="panel"><div class="section-head panel-pad"><h2>Active Projects</h2><button class="btn" data-route="projects">View All</button></div><div class="list">${projects}</div></div><div class="panel"><div class="section-head panel-pad"><h2>SRS Vision Members</h2><button class="btn" data-route="teams">Manage</button></div><div class="list">${people}</div></div></div></section>
      <section class="section"><div class="panel"><div class="section-head panel-pad"><div><h2>Quick Workspace Controls</h2><small>Management dashboards remain separate from creative tool dashboards</small></div></div><div class="launch-grid panel-pad">${[['social-media','◉ Social Media','Channels & alerts'],['notifications','🔔 Notifications','Unified event inbox'],['money-transfer','💸 Money Transfer','12-member approvals'],['database','◉ Database','Realtime health'],['reports','▥ Reports','Business analytics'],['calendar','📅 Calendar','Events & schedules']].map(x=>`<button class="launch" data-route="${x[0]}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></div></section>`);
  }

  function renderTool(key){
    const v=TOOLS[key];
    const links=(key==='ai-tools')?AI_LINKS.map(x=>`<div class="row"><div><b>${esc(x[0])}</b><small style="display:block;color:#86a4be">${esc(x[2])}</small></div><button class="btn primary" data-external="${x[1]}">Open</button></div>`).join(''):v.features.map((f,i)=>`<button class="feature" data-tool-action="${esc(f)}"><span class="fi">${['✦','◉','▧','▶','⌁','✓'][i%6]}</span><b>${esc(f)}</b><small>Open dedicated workspace</small></button>`).join('');
    return layout(`<div class="tool-header"><div class="tool-title"><div class="tool-icon">${v.icon}</div><div><div class="eyebrow">SRS VISION · DEDICATED DASHBOARD</div><h1>${esc(v.title)}</h1><p>${esc(v.desc)}</p></div></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-tool-action="${esc('New '+v.title+' Project')}">＋ New</button></div></div>
      <section class="tool-hero"><div class="panel panel-pad"><div class="eyebrow">FOCUSED WORKSPACE</div><h2 style="font-size:28px;margin:10px 0">Run ${esc(v.title)} separately from the main dashboard.</h2><p style="color:#9db5cc">This workspace is intentionally independent so the main dashboard stays clean and fast.</p><div class="pills"><span class="pill">Separate navigation</span><span class="pill">Shared SRS Vision data</span><span class="pill">Expandable tools</span></div></div><div class="tool-art"><img src="assets/srs-vision-logo.png" alt="SRS Vision"></div></section>
      <section class="section"><div class="panel"><div class="section-head panel-pad"><h2>${esc(v.title)} Tools</h2><button class="btn" data-route="dashboard">Back</button></div>${key==='ai-tools'?`<div class="list">${links}</div>`:`<div class="feature-grid panel-pad">${links}</div>`}</div></section>`);
  }

  function renderTeams(){
    const memberCards=state.members.map((m,i)=>`<div class="member"><div class="member-top"><span class="avatar">${initials(m.name)}</span><div><b>${esc(m.name)}</b><small>${esc(m.role)} · ${esc(m.service)}</small></div></div><small style="display:block;margin-top:8px">${esc(m.description||'SRS Vision team member')}</small><div class="member-actions"><button class="btn" data-edit-member="${i}">✎ Edit</button><button class="btn" data-custom-member="${i}">⚙ Customise</button></div></div>`).join('');
    return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · TEAM MANAGEMENT</div><h1>Teams & Members</h1><p>One team: <b>SRS VISION</b> · ${state.members.length} members</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-add-member="1">＋ Add Member</button></div></div><section class="panel"><div class="section-head panel-pad"><div><h2>SRS Vision Members</h2><small>All members belong to the same SRS Vision team</small></div></div><div class="member-grid">${memberCards}</div></section>`);
  }

  function renderSocial(){
    const cards=state.socialChannels.map((c,i)=>`<div class="channel"><div class="channel-top"><div class="channel-icon">${esc(c.icon)}</div><span class="status ${c.connected?'ok':'warn'}">${c.connected?'Connected':'Not connected'}</span></div><b>${esc(c.name)}</b><small>${esc(c.type)}</small><div class="actions" style="margin-top:10px"><button class="btn" data-toggle-channel="${i}">${c.connected?'Disconnect':'Connect'}</button><button class="btn" data-external="${c.url}">Open</button></div></div>`).join('');
    return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · SOCIAL MEDIA</div><h1>Social Media Hub</h1><p>Keep WhatsApp, Instagram, YouTube, Pinterest and other channels in one dedicated dashboard.</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-social-test="1">🔔 Test Notification</button></div></div><section class="panel"><div class="section-head panel-pad"><h2>Channel Slots</h2><small>Connector-ready; private platform notifications need OAuth/webhooks</small></div><div class="channel-grid">${cards}</div></section><section class="section"><div class="two-col"><div class="panel panel-pad"><div class="section-head"><h2>Post Scheduler</h2></div><div class="form-grid"><div class="field"><label>Platform</label><select id="post-platform">${state.socialChannels.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Publish date</label><input id="post-date" type="date"></div><div class="field full"><label>Caption</label><textarea id="post-caption" placeholder="Write your social post…"></textarea></div></div><div class="modal-foot"><button class="btn primary" data-schedule-post="1">Schedule Post</button></div></div><div class="panel panel-pad"><div class="section-head"><h2>Social Notifications</h2><button class="btn" data-route="notifications">View All</button></div>${state.notifications.filter(n=>n.source==='Social Media').slice(0,5).map(n=>`<div class="row"><div><b>${esc(n.title)}</b><small style="display:block;color:#86a4be">${esc(n.detail)}</small></div><span class="status ${n.read?'':'warn'}">${n.read?'Read':'New'}</span></div>`).join('')||'<div class="notice">No social notifications yet.</div>'}</div></div></section>`);
  }

  function renderNotifications(){
    const items=state.notifications.map((n,i)=>`<div class="row"><div><b>${esc(n.title)}</b><small style="display:block;color:#86a4be">${esc(n.source)} · ${esc(n.detail)}</small></div><div class="actions"><span class="status ${n.read?'':'warn'}">${n.read?'Read':'New'}</span><button class="btn" data-read-notification="${i}">${n.read?'✓':'Mark read'}</button></div></div>`).join('');
    return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · NOTIFICATION CENTER</div><h1>Notifications</h1><p>One inbox for SRS Vision system, social, finance, project and team events.</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-notification-test="1">＋ Test Notification</button></div></div><section class="panel"><div class="list">${items||'<div class="panel-pad"><div class="notice">No notifications yet.</div></div>'}</div></section>`);
  }

  function approvalSummary(t){const a=t.approvals||[];return {allow:a.filter(x=>x.decision==='ALLOW').length,deny:a.filter(x=>x.decision==='DENY').length,pending:a.filter(x=>x.decision==='PENDING').length}}
  function renderMoney(){
    const reqs=state.transfers||[]; const requestCards=reqs.map(t=>{const s=approvalSummary(t);const approved=t.status==='APPROVED_FOR_EXECUTION'; const blocked=t.status==='BLOCKED'; const approvers=state.members.map((m,i)=>{const a=(t.approvals||[])[i]||{decision:'PENDING'};return `<div class="approval"><div><b>${esc(m.name)}</b><small style="display:block;color:#7f9ebb">${a.decision}</small></div>${t.status==='PENDING'?`<div class="approval-actions"><button class="allow" data-transfer="${t.id}" data-member="${i}" data-decision="ALLOW">Allow</button><button class="deny" data-transfer="${t.id}" data-member="${i}" data-decision="DENY">Deny</button></div>`:''}</div>`}).join('');return `<div class="srs-transfer-placeholder"></div><div class="panel" style="margin-top:14px"><div class="section-head panel-pad"><h2>Transfer Requests</h2><span class="status ${blocked?'err':approved?'ok':'warn'}">${esc(t.status)}</span></div><div class="panel-pad"><b>${esc(t.recipient)} · ${money(t.amount)}</b><small style="display:block;color:#86a4be">Requested by ${esc(t.requester)} · ${esc(t.account)} · ${esc(t.purpose)}</small><div class="pills"><span class="pill">Allow ${s.allow}/12</span><span class="pill">Deny ${s.deny}</span><span class="pill">Pending ${s.pending}</span></div><div class="approval-grid" style="margin-top:10px">${approvers}</div>${approved?'<div class="notice good" style="margin-top:10px">All 12 members approved. The request is eligible for secure provider execution; this front-end does not execute a bank transfer.</div>':''}${blocked?'<div class="notice warn" style="margin-top:10px">Transfer blocked. At least one member selected Deny, so no transfer execution is allowed.</div>':''}</div></div>`}).join('');
    return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · SECURE WORKFLOW</div><h1>Money Transfer</h1><p>Create a transfer request and require all 12 SRS Vision members to approve it. One Deny blocks it.</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button></div></div><section class="panel panel-pad"><div class="section-head"><h2>New Transfer Request</h2></div><div class="form-grid"><div class="field"><label>Requester</label><select id="tr-requester">${state.members.map(m=>`<option>${esc(m.name)}</option>`).join('')}</select></div><div class="field"><label>Recipient</label><input id="tr-recipient" placeholder="Recipient name"></div><div class="field"><label>Mobile / UPI / Account reference</label><input id="tr-account" placeholder="Recipient number, UPI ID or reference"></div><div class="field"><label>Amount (₹)</label><input id="tr-amount" type="number" min="1" placeholder="0"></div><div class="field full"><label>Purpose</label><textarea id="tr-purpose" placeholder="Why is this transfer required?"></textarea></div></div><div class="notice warn" style="margin-top:12px">Approval is an internal SRS Vision control. Actual bank/UPI execution and OTP/2FA remain with the payment provider.</div><div class="modal-foot"><button class="btn primary" data-create-transfer="1">Create Approval Request</button></div></section>${requestCards||'<section class="panel panel-pad" style="margin-top:14px"><div class="notice">No transfer requests yet.</div></section>'}`);
  }

  function renderDatabase(){
    const d=appStatus();return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · DATABASE</div><h1>Database & Realtime</h1><p>Check Supabase status, refresh shared data and keep the app usable with a local fallback.</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-db-check="1">Check Connection</button></div></div><div class="grid4"><div class="kpi ${d.connected?'green':'pink'}"><span>Connection</span><b>${d.connected?'LIVE':'OFFLINE'}</b><small>${d.lastError?esc(d.lastError):'Supabase client'}</small></div><div class="kpi ${d.realtime?'cyan':'purple'}"><span>Realtime</span><b>${d.realtime?'ON':'READY'}</b><small>Postgres Changes</small></div><div class="kpi"><span>Pending</span><b>${d.pending?'YES':'NO'}</b><small>Local save queue</small></div><div class="kpi"><span>Last Update</span><b>${d.lastUpdatedAt?new Date(d.lastUpdatedAt).toLocaleTimeString('en-IN'):'—'}</b><small>Shared state</small></div></div><div class="two-col"><section class="panel panel-pad"><div class="section-head"><h2>Connection Controls</h2></div><div class="actions"><button class="btn primary" data-db-sync="1">↻ Sync Now</button><button class="btn" data-db-refresh="1">↺ Refresh Server Data</button><button class="btn" data-db-export="1">⇩ Export Backup</button></div><div class="notice" style="margin-top:12px">The app uses an anonymous Supabase session, then reads/writes the shared srs_vision_state row. Local browser storage remains available when the server is unreachable.</div></section><section class="panel panel-pad"><div class="section-head"><h2>Required Setup</h2></div><div class="list"><div class="row"><div><b>Anonymous Sign-Ins</b><small style="display:block;color:#86a4be">Enable Anonymous provider</small></div><span class="status warn">Required</span></div><div class="row"><div><b>database.sql</b><small style="display:block;color:#86a4be">Run the included SQL in Supabase</small></div><span class="status warn">Required</span></div><div class="row"><div><b>Realtime publication</b><small style="display:block;color:#86a4be">Add public.srs_vision_state to supabase_realtime</small></div><span class="status warn">Required</span></div></div></section></div>`);
  }

  function simpleRecords(route,title,desc,fields){
    const arr=state[route]||[];const rows=arr.map((x,i)=>`<tr>${fields.map(f=>`<td>${esc(x[f]??'')}</td>`).join('')}<td><button class="btn" data-edit-record="${route}:${i}">Edit</button><button class="btn red" data-delete-record="${route}:${i}">Delete</button></td></tr>`).join('');return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · WORKSPACE</div><h1>${title}</h1><p>${desc}</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-add-record="${route}">＋ Add</button></div></div><section class="panel"><div class="table-wrap"><table class="table"><thead><tr>${fields.map(f=>`<th>${f}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows||`<tr><td colspan="${fields.length+1}">No records yet.</td></tr>`}</tbody></table></div></section>`);
  }
  function renderReports(){const revenue=state.projects.reduce((a,p)=>a+Number(p.value||0),0);const active=state.projects.filter(p=>p.status!=='Completed').length;return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · REPORTS</div><h1>Reports & Analytics</h1><p>Simple business metrics from the shared project and team state.</p></div><button class="btn" data-route="dashboard">← Main Dashboard</button></div><div class="grid4"><div class="kpi blue"><span>Pipeline Value</span><b>${money(revenue)}</b><small>Project values</small></div><div class="kpi green"><span>Completed</span><b>${state.projects.filter(p=>p.status==='Completed').length}</b><small>Projects</small></div><div class="kpi cyan"><span>Active / Open</span><b>${active}</b><small>Projects</small></div><div class="kpi purple"><span>Members</span><b>${state.members.length}</b><small>SRS Vision</small></div></div><section class="section"><div class="two-col"><div class="panel"><div class="section-head panel-pad"><h2>Projects</h2></div><div class="list">${state.projects.map(p=>`<div class="row"><div><b>${esc(p.name)}</b><small style="display:block;color:#86a4be">${esc(p.client)} · ${esc(p.service)}</small></div><span class="status ${p.status==='Completed'?'ok':'warn'}">${esc(p.status)}</span></div>`).join('')}</div></div><div class="panel panel-pad"><h2>Finance Summary</h2><p style="color:#86a4be">Pipeline ${money(revenue)} · Clients ${state.clients.length} · Services ${state.services.length}</p><div class="notice">For real banking data, connect a secure provider/API on a server; do not put secret banking credentials in the browser.</div></div></div></section>`)}
  function renderCalendar(){const rows=state.events.map((e,i)=>`<div class="row"><div><b>${esc(e.title)}</b><small style="display:block;color:#86a4be">${esc(e.date)} ${esc(e.time||'')} · ${esc(e.type||'Event')}</small></div><div class="actions"><span class="status ${e.status==='Completed'?'ok':'warn'}">${esc(e.status||'Scheduled')}</span><button class="btn red" data-delete-event="${i}">Delete</button></div></div>`).join('');return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · CALENDAR</div><h1>Calendar</h1><p>Manage deadlines, meetings, events and announcements.</p></div><div class="actions"><button class="btn" data-route="dashboard">← Main Dashboard</button><button class="btn primary" data-add-event="1">＋ Add Event</button></div></div><section class="panel"><div class="list">${rows||'<div class="panel-pad"><div class="notice">No events yet.</div></div>'}</div></section>`)}
  function renderSettings(){return layout(`<div class="tool-header"><div><div class="eyebrow">SRS VISION · SETTINGS</div><h1>Settings</h1><p>Workspace identity and local controls.</p></div><button class="btn" data-route="dashboard">← Main Dashboard</button></div><section class="panel panel-pad"><div class="form-grid"><div class="field"><label>Company name</label><input id="set-name" value="${esc(state.company.name)}"></div><div class="field"><label>Tagline</label><input id="set-tagline" value="${esc(state.company.tagline)}"></div></div><div class="modal-foot"><button class="btn primary" data-save-settings="1">Save Settings</button></div></section>`)}

  function modal(title,body){return `<div class="modal-backdrop" id="modal"><div class="modal"><h3>${esc(title)}</h3><div class="sub">SRS Vision Workspace</div>${body}<div class="modal-foot"><button class="btn ghost" data-close-modal="1">Cancel</button><button class="btn primary" data-save-modal="1">Save</button></div></div></div>`}
  let modalSave=null;
  function openRecordModal(route,index){const isNew=index<0;const base=isNew?{}:state[route][index];const fields=route==='projects'?[['name','Project Name'],['client','Client'],['service','Service'],['status','Status'],['due','Due Date'],['value','Value'],['owner','Owner']]:route==='clients'?[['name','Client Name'],['service','Service'],['status','Status'],['contact','Contact']]:[['name','Service Name'],['description','Description'],['status','Status']];const form=fields.map(([k,l])=>`<div class="field"><label>${l}</label><input id="m_${k}" value="${esc(base[k]??'')}"></div>`).join('');document.getElementById('modal-root').innerHTML=modal(isNew?'Add '+route.slice(0,-1):'Edit '+route,`<div class="form-grid">${form}</div>`);modalSave=()=>{const obj={id:base.id||route.slice(0,-1)+'_'+Date.now()};fields.forEach(([k])=>obj[k]=document.getElementById('m_'+k)?.value?.trim()||'');if(route==='projects')obj.value=Number(obj.value||0);state[route]=isNew?[...state[route],obj]:state[route].map((x,i)=>i===index?obj:x);document.getElementById('modal-root').innerHTML='';modalSave=null;commit([route])};}
  function openMemberModal(index){const isNew=index<0, m=isNew?{name:'',role:'SRS Vision Member',service:'Creative Team',description:'',skills:'',phone:'',notes:''}:state.members[index];const body=`<div class="form-grid"><div class="field"><label>Name</label><input id="m_name" value="${esc(m.name)}"></div><div class="field"><label>Role</label><input id="m_role" value="${esc(m.role)}"></div><div class="field"><label>Service</label><input id="m_service" value="${esc(m.service)}"></div><div class="field"><label>Phone</label><input id="m_phone" value="${esc(m.phone||'')}"></div><div class="field full"><label>Description</label><textarea id="m_description">${esc(m.description||'')}</textarea></div><div class="field full"><label>Skills</label><input id="m_skills" value="${esc(m.skills||'')}"></div><div class="field full"><label>Notes</label><textarea id="m_notes">${esc(m.notes||'')}</textarea></div></div>`;document.getElementById('modal-root').innerHTML=modal(isNew?'Add SRS Vision Member':'Edit '+m.name,body);modalSave=()=>{const n={id:m.id||'m_'+Date.now(),name:document.getElementById('m_name').value.trim()||'SRS Vision Member',role:document.getElementById('m_role').value.trim()||'SRS Vision Member',service:document.getElementById('m_service').value.trim()||'Creative Team',phone:document.getElementById('m_phone').value.trim(),description:document.getElementById('m_description').value.trim(),skills:document.getElementById('m_skills').value.trim(),notes:document.getElementById('m_notes').value.trim(),active:true};state.members=isNew?[...state.members,n]:state.members.map((x,i)=>i===index?n:x);document.getElementById('modal-root').innerHTML='';modalSave=null;commit(['members'])}}
  function openEventModal(){document.getElementById('modal-root').innerHTML=modal('Add Calendar Event',`<div class="form-grid"><div class="field"><label>Title</label><input id="m_title"></div><div class="field"><label>Date</label><input id="m_date" type="date"></div><div class="field"><label>Time</label><input id="m_time" type="time"></div><div class="field"><label>Type</label><input id="m_type" value="Event"></div><div class="field full"><label>Notes</label><textarea id="m_notes"></textarea></div></div>`);modalSave=()=>{state.events.unshift({id:'e_'+Date.now(),title:document.getElementById('m_title').value.trim(),date:document.getElementById('m_date').value,time:document.getElementById('m_time').value,type:document.getElementById('m_type').value.trim(),status:'Scheduled',notes:document.getElementById('m_notes').value.trim()});document.getElementById('modal-root').innerHTML='';modalSave=null;commit(['events'])}}

  function render(){document.body.className='';if(TOOLS[currentRoute])document.body.classList.add('tool-page');let content;switch(currentRoute){case 'dashboard':content=renderMain();break;case 'teams':content=renderTeams();break;case 'social-media':content=renderSocial();break;case 'notifications':content=renderNotifications();break;case 'money-transfer':content=renderMoney();break;case 'database':content=renderDatabase();break;case 'reports':content=renderReports();break;case 'calendar':content=renderCalendar();break;case 'settings':content=renderSettings();break;case 'projects':content=simpleRecords('projects','Projects','Manage project pipeline, assignments, budgets and completion.', ['name','client','service','status','due','value','owner']);break;case 'clients':content=simpleRecords('clients','Clients','Manage client records and contacts.', ['name','service','status','contact']);break;case 'services':content=simpleRecords('services','Services','Manage service catalog and offerings.', ['name','description','status']);break;default:content=TOOLS[currentRoute]?renderTool(currentRoute):simpleRecords('projects','Workspace','Open a dashboard from the main screen.', ['name','client','status']);}return content}

  document.addEventListener('click',function(e){
    const route=e.target.closest('[data-route]');if(route){e.preventDefault();setRoute(route.getAttribute('data-route'));return;}
    const ext=e.target.closest('[data-external]');if(ext){e.preventDefault();openExternal(ext.getAttribute('data-external'));return;}
    const ta=e.target.closest('[data-tool-action]');if(ta){toast(ta.getAttribute('data-tool-action')+' opened');return;}
    if(e.target.closest('[data-toggle-channel]')){const i=Number(e.target.closest('[data-toggle-channel]').getAttribute('data-toggle-channel'));state.socialChannels[i].connected=!state.socialChannels[i].connected;persist(['socialChannels']);toast(state.socialChannels[i].connected?'Channel connected':'Channel disconnected');render();return;}
    if(e.target.closest('[data-social-test]')||e.target.closest('[data-notification-test]')){state.notifications.unshift({id:'n_'+Date.now(),source:'Social Media',title:'SRS Vision platform notification',detail:'Test notification received successfully.',createdAt:new Date().toISOString(),read:false});commit(['notifications']);return;}
    if(e.target.closest('[data-read-notification]')){const i=Number(e.target.closest('[data-read-notification]').getAttribute('data-read-notification'));state.notifications[i].read=true;commit(['notifications']);return;}
    if(e.target.closest('[data-schedule-post]')){const platform=document.getElementById('post-platform').value,caption=document.getElementById('post-caption').value.trim();if(!caption)return toast('Write a caption first');state.notifications.unshift({id:'n_'+Date.now(),source:'Social Media',title:'Post scheduled',detail:`${platform} · ${caption.slice(0,80)}`,createdAt:new Date().toISOString(),read:false});commit(['notifications']);return;}
    if(e.target.closest('[data-add-member]')){openMemberModal(-1);return;}
    if(e.target.closest('[data-edit-member]')){openMemberModal(Number(e.target.closest('[data-edit-member]').getAttribute('data-edit-member')));return;}
    if(e.target.closest('[data-custom-member]')){const i=Number(e.target.closest('[data-custom-member]').getAttribute('data-custom-member'));openMemberModal(i);return;}
    if(e.target.closest('[data-add-record]')){const r=e.target.closest('[data-add-record]').getAttribute('data-add-record');openRecordModal(r,-1);return;}
    if(e.target.closest('[data-edit-record]')){const [r,i]=e.target.closest('[data-edit-record]').getAttribute('data-edit-record').split(':');openRecordModal(r,Number(i));return;}
    if(e.target.closest('[data-delete-record]')){const [r,i]=e.target.closest('[data-delete-record]').getAttribute('data-delete-record').split(':');if(confirm('Delete this record?')){state[r].splice(Number(i),1);commit([r])}return;}
    if(e.target.closest('[data-add-event]')){openEventModal();return;}
    if(e.target.closest('[data-delete-event]')){const i=Number(e.target.closest('[data-delete-event]').getAttribute('data-delete-event'));state.events.splice(i,1);commit(['events']);return;}
    if(e.target.closest('[data-save-settings]')){state.company.name=document.getElementById('set-name').value.trim()||'SRS Vision';state.company.tagline=document.getElementById('set-tagline').value.trim()||'YOUR VISION · OUR CREATION';commit(['company']);return;}
    if(e.target.closest('[data-create-transfer]')){const rec=document.getElementById('tr-recipient').value.trim(),acc=document.getElementById('tr-account').value.trim(),amt=Number(document.getElementById('tr-amount').value||0),purpose=document.getElementById('tr-purpose').value.trim(),requester=document.getElementById('tr-requester').value;if(!rec||!acc||!amt||!purpose)return toast('Enter recipient, account reference, amount and purpose');state.transfers.unshift({id:'tr_'+Date.now(),requester,recipient:rec,account:acc,amount:amt,purpose,status:'PENDING',createdAt:new Date().toISOString(),approvals:state.members.map(m=>({memberId:m.id,memberName:m.name,decision:'PENDING'}))});state.notifications.unshift({id:'n_'+Date.now(),source:'Money Transfer',title:'Approval request created',detail:`${rec} · ${money(amt)} · 12 approvals required`,createdAt:new Date().toISOString(),read:false});commit(['transfers','notifications']);return;}
    const decision=e.target.closest('[data-decision]');if(decision){const id=decision.getAttribute('data-transfer'),idx=Number(decision.getAttribute('data-member')),d=decision.getAttribute('data-decision'),t=state.transfers.find(x=>x.id===id);if(!t||t.status!=='PENDING')return;const a=t.approvals[idx];if(!a)return;a.decision=d;const sum=approvalSummary(t);if(d==='DENY'||sum.deny>0){t.status='BLOCKED';state.notifications.unshift({id:'n_'+Date.now(),source:'Money Transfer',title:'Transfer blocked',detail:`${t.recipient} · ${a.memberName} selected Deny`,createdAt:new Date().toISOString(),read:false});}else if(sum.allow===12){t.status='APPROVED_FOR_EXECUTION';state.notifications.unshift({id:'n_'+Date.now(),source:'Money Transfer',title:'12/12 approvals received',detail:`${t.recipient} · ${money(t.amount)} · eligible for secure provider execution`,createdAt:new Date().toISOString(),read:false});}commit(['transfers','notifications']);return;}
    if(e.target.closest('[data-db-check]')){window.srsDB?.health?.().then(()=>render());return;}
    if(e.target.closest('[data-db-sync]')){window.srsDB?.saveAll?.(state).then(()=>render());return;}
    if(e.target.closest('[data-db-refresh]')){window.srsDB?.refresh?.().then(()=>{state=loadState();render();});return;}
    if(e.target.closest('[data-db-export]')){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='srs-vision-backup.json';a.click();URL.revokeObjectURL(url);return;}
    if(e.target.closest('[data-save-modal]')){if(modalSave)modalSave();return;}
    if(e.target.closest('[data-close-modal]')){document.getElementById('modal-root').innerHTML='';modalSave=null;return;}
  });

  window.SRS_APP={getState:()=>clone(state),replaceState:(next,shouldRender=true)=>{state=mergeDefaults(next);localStorage.setItem(stateKey,JSON.stringify(state));if(shouldRender)render()}};
  window.esc=esc;window.money=money;window.setSrsRoute=setRoute;
  window.addEventListener('srs:dbstatus',()=>{if(currentRoute==='database')render()});
  window.addEventListener('popstate',()=>{currentRoute=(location.hash||'#dashboard').slice(1)||'dashboard';render()});
  window.addEventListener('hashchange',()=>{currentRoute=(location.hash||'#dashboard').slice(1)||'dashboard';render()});
  window.addEventListener('storage',e=>{if(e.key===stateKey&&e.newValue){try{state=mergeDefaults(JSON.parse(e.newValue));render()}catch{}}});

  // Start Supabase connection without blocking the UI.
  window.srsDB?.connect?.().then(()=>{if(currentRoute==='database')render()}).catch(()=>{});
  render();
})();
